name: Fetch and Extract Proxies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'
  

jobs:
  fetch-text:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run script
      run: node .github/scripts/fetchAndExtract.js

    - name: Commit and push changes
      run: |
            git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
            git config --local user.name "${GITHUB_ACTOR}"
            git add proxies.yaml
            git commit -m "Update extracted content [skip ci]"
            git push
