name: Fetch and Extract Proxies

on:
  workflow_dispatch:
  schedule:
    - cron: '40 6 * * *'
  

jobs:
  fetch-text:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

   # - name: Clear npm cache
   #   run: |
   #         npm cache clean --force
   #         rm -rf node_modules
   #         rm -f package-lock.json

    - name: Install dependencies
      run: npm install

    - name: Run script
      run: node .github/scripts/fetchAndExtract.js

    - name: Commit and push changes
      run: |
            git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
            git config --local user.name "${GITHUB_ACTOR}"
            git add proxies.yaml
            git add package.json  
            git add package-lock.json  
            git commit -m "Update dependencies and extracted content [skip ci]"
            git pull origin main
            git push -u origin main
